"""Added image edited url

Revision ID: 0b997959aef0
Revises: 242a2d256705
Create Date: 2023-09-07 21:31:12.404451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b997959aef0'
down_revision: Union[str, None] = '242a2d256705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('edited_cloudinary_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'edited_cloudinary_url')
    # ### end Alembic commands ###
